# Generated by Django 3.1.7 on 2021-03-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user1_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
